apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:6IWyf6EvGrY=,iv:PsiJeX6PMk40oVLVl6a//KS3dAZG+54jC3tn0a7SRcY=,tag:UOKIQPLWIQsKpoTIaPuRcQ==,type:str]
    admin-user: ENC[AES256_GCM,data:FtEvPPE=,iv:kEa9iM2B8IgKzf5kGG5z5h8QtqEPf3oeBo/yjFC1dSM=,tag:WwBOEAMYFAYpCO0OYItb5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hrkq9v334f32a2xl9lqmm08vhhsn64uehpxs8u7v36w9jxfnu5s6jhfwl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0OGh5YW5IbUNTcVRhRmdW
            anNHZHB3d2ZpbEl0YW10eXZwZ0VZUWhKQ2dVCjJuemdhUGxjeTY2dnVMUVV5S3dW
            dis0VW01N0xCQ1QyNXpZTVlHOVNnSXcKLS0tIEh4ZDVNWVQ4TVc3Ulpvd0o5SUYz
            NXpmeE9uSmp0aHBxZlFqbnlWNlR1cDgK9CMvjdUMpajXvSur9IndbdEHZiJDQthJ
            nzqyyXje1ji8AidJORfU3LZ0qa1y2davu4VtVOss/nlTbUMq1FzWow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-25T02:10:19Z"
    mac: ENC[AES256_GCM,data:Z+YWK1X1903n/61sI/z2HIc15myh4D0sd5pBC63b8PER0u1pWMpZO3qnKAdsqjriBdfL2/AbvADGLfcIdNKSoEsGoLDP7vNPWC4iugOUYsN0gDr++QVTxaQ7SkH/4gkzge/kIPVHOR3kl/C7rJoCA7uevuVQ5uk/aFfq8nIWPf4=,iv:lx2BLr4lbArVMlxFp91aZiHO+oYXmwT9VEobtlOdARc=,tag:Usxp2FQ25+9tmLqg/maeMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
