apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Q76lHr17wbu6CX5UPgBXINNX+uT33YLad9eSKsproilBUZ2eJaw8Og==,iv:61rI0yQQ/+aafNPWY7Q6g0kvcUZCuW/1WHpy4TU9v6s=,tag:gIuV35K+WaPi+5gkrpC59Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hrkq9v334f32a2xl9lqmm08vhhsn64uehpxs8u7v36w9jxfnu5s6jhfwl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzU3lKOGdkWVVKaFNDRXJN
            MlJSZHZpSU1uZzVITjgwNk8yNU1jZk81bEcwCm5pU3lLRXgrYnN4aEwzN1JjWXFo
            ekxlYytnU1dSUldpeEtPb21mRnF2MUEKLS0tIGNWTkJ2VUxhSXhsOFpXdVE2Mytz
            ZTI1VmxFOEM0T3RLM1B2WUg2UlFWaFkKNQowKBTbpuiUYrw1ywx6egrIxDmk5CnX
            FI1c9565Hg9cwlxJKYBEEvTzMMiSxrF4YK/BCYuYCDib3j9h7pD7WQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-25T02:10:16Z"
    mac: ENC[AES256_GCM,data:rHXgxcNH64ao/eo+6OF/qlNRtRfZOIfhAS7ggamEccGCUqBW09cPLtgIJg6I4JOGT7t8nrkcpJuAHd+Hrb1v9FhYxF+I/pHEtH0DDpHeLgXgr0yd01OM0x9pTCJO0iIQQRg1CCVx5udHCVtaISMPs27792XOHWUdrvYs/iQ4LsI=,iv:BI2Z6uEynPyyn0NuEutnj/md1/M3vrzrLwV7ZgoLNTE=,tag:pdJlw3moD6lR1xR0VCHn5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
