apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:zIwE+SuwWTSzesxwD/mspXbpWHGhsvg+cTyE1lXs17OEAvg2IXxtIfkOdu8xLFWIEzIk0iZ5/Eikzy00,iv:MXjIS9jCeiOCYYJiZW0B8m3rsRx586+2hR6rfl1McJI=,tag:empGSIoBs7hCGJZJdd84VA==,type:str]
    username: ENC[AES256_GCM,data:vtykYWo=,iv:9tTsLOEjr0Y67G52yTmi/uvlqTsiuDMcKM9ZDjlBwzs=,tag:bVoO194zkE7+qbaerdOqDw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hrkq9v334f32a2xl9lqmm08vhhsn64uehpxs8u7v36w9jxfnu5s6jhfwl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQU1k4MS9Ka0Jtc2RhdG5O
            Rnd2TVcveFR1Z1o4WUY4MmNsUHp2cjhEeVc0CnFFM1pRR3BscFlFak82VnYvZ0Uz
            VDVOTEJ1QmRvZzVRL0RZbmpuMWQxamsKLS0tIE9FNWNDaEYyTXlqaWk5SGVHUDk3
            OFMrbWFHVkFFKytWRTNMMXVDaE4yVEUKYj9xhppSlvmco6PisN39yzsn7H15ev/9
            vvnbq0NvUf+X8nMaHS+h83WVZZkIlzBWV0YvQR8d7hYhebyaru3W5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T21:37:32Z"
    mac: ENC[AES256_GCM,data:rHbv7faND6Zi44ZVeMMbqCfSmbEy411BcsZMBQ3RoxQf0ivM/xjmzg4sNd7+L+qvzPGp3lC12kiiDtDGe3Kq4G44LfcPrslWKPCgGtYdxXwfvDYcveRHi/pcSnkhzmZntYsd4GrOc0YdGpcE1KzO7RQVuLIoQn2/aqw1dtLrcK4=,iv:dbpoWCku+Nb/qYEWH+JPoNXtu75x2fBZNBX1vJFDnps=,tag:bFqHge8B7c6lc7+y9oocpA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
