apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:/U2QJS9ioxS2xDWO,iv:f4lmTs7Dp/Lxc2zvAOfuYF5aeEHK581JgE6nXuHxo6k=,tag:k7PNVtN//Qg0rIv4HikouA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hrkq9v334f32a2xl9lqmm08vhhsn64uehpxs8u7v36w9jxfnu5s6jhfwl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcEN6bnNqMld2NzExK1NI
            aVBDUlJ5Y3BYS0hwRUNzakxUM1B5dGUzT3pzCi9pLzU1WWx4b2M4YlMvVndVTS9O
            ZC9NWHNZNENuTktDSFJEY05NZG5MR3MKLS0tIHIwQ1pMVjRWR3hOOEdKQktKL0pR
            dzkxVUI5SDQvUDZmaXdVdlNKNnV5NG8K9vsLmo9okTWVkntBZO2mtwx6J6HaMC+S
            vWiY87R6I8Fl+n3bsLcw7pW+VJd07/dm/ZcdsetwUk0Yv3vNzPrwtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T21:37:26Z"
    mac: ENC[AES256_GCM,data:IZlvIMG1+f5tFHzHLg/ay7X+10+7b0RPB96Csoq0jMmK0VN2nqx34Tn8kw+wOTLXs9gJ/SPN4fM33yms3r524VNiECSSCVqbwyJ/sCzSJETSfWPPbt6G7hyCDSS3ZKG7aa9pxZL4P6SRlhcZGuNXmwzZh8vKcn298F8Y/38PnZ8=,iv:hKRlJUUmdaROxQV2Yu0pbpzXRL5TiuorqP4C9TPCHjg=,tag:RhjcHDPU2JDIu8z0HlMvbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
